version: "2"
services:
    hadoop1:
        image: hadoop:HA
        container_name: hadoop1
        hostname: hadoop1
        depends_on:
            - zk1
            - zk2
            - zk3
        networks:
            hadoop:
                aliases:
                    - master
                    - nn1
                    - rm1
        environment:
            ZK_SERVERS: zk1:2181,zk2:2181,zk3:2181
            HADOOP_WORKER_NAMES: hadoop1 hadoop2 hadoop3
            HDFS_JOURNAL_NODES: hadoop1:8485,hadoop2:8485,hadoop3:8485
        ports:
            - "50010:50010"
            - "50020:50020"
            - "50070:50070"
            - "50075:50075"
            - "50090:50090"
            - "8020:8020"
            - "9000:9000"
            - "10020:10020"
            - "8030:8030"
            - "19888:19888"
            - "8031:8031"
            - "8032:8032"
            - "8033:8033"
            - "8040:8040"
            - "8042:8042"
            - "8088:8088"
            - "49707:49707"
            - "2122:2122"
            - "8485:8485"
        command: [ "-d" ]
        
    hadoop2: 
        image: hadoop:HA
        container_name: hadoop2
        hostname: hadoop2
        depends_on:
            - zk1
            - zk2
            - zk3
        networks:
            hadoop:
                aliases:
                    - standby
                    - nn2
                    - rm2
        environment:
            ZK_SERVERS: zk1:2181,zk2:2181,zk3:2181
            HADOOP_WORKER_NAMES: hadoop1 hadoop2 hadoop3
            HDFS_JOURNAL_NODES: hadoop1:8485,hadoop2:8485,hadoop3:8485
        expose:
            - "50010"
            - "50020"
            - "50070"
            - "50075"
            - "50090"
            - "8020"
            - "9000"
            - "10020"
            - "8030"
            - "19888"
            - "8031"
            - "8032"
            - "8033"
            - "8040"
            - "8042"
            - "8088"
            - "49707"
            - "2122"
            - "8485"
        command: [ "-d" ]
        
    hadoop3: 
        image: hadoop:HA
        container_name: hadoop3
        hostname: hadoop3
        depends_on:
            - zk1
            - zk2
            - zk3
        networks:
            hadoop:
                aliases:
                    - slave1
        environment:
            ZK_SERVERS: zk1:2181,zk2:2181,zk3:2181
            HADOOP_WORKER_NAMES: hadoop1 hadoop2 hadoop3
            HDFS_JOURNAL_NODES: hadoop1:8485,hadoop2:8485,hadoop3:8485 
        expose:
            - "50010"
            - "50020"
            - "50070"
            - "50075"
            - "50090"
            - "8020"
            - "9000"
            - "10020"
            - "8030"
            - "19888"
            - "8031"
            - "8032"
            - "8033"
            - "8040"
            - "8042"
            - "8088"
            - "49707"
            - "2122"
            - "8485"
        command: [ "-d" ]
    zk1:
        image: zookeeper:latest
        container_name: zk1
        hostname: zk1
        networks:
            hadoop:
                aliases:
                  - zk1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk2:
        image: zookeeper:latest
        container_name: zk2
        hostname: zk2
        networks:
            hadoop:
                aliases:
                  - zk2
        ports:
            - 2182:2181
        expose:
            - 2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk3:
        image: zookeeper:latest
        container_name: zk3
        hostname: zk3
        networks:
            hadoop:
                aliases:
                  - zk3
        ports:
            - 2183:2181
        expose:
            - 2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
networks: 
    hadoop:
